try{
    /*let num = 10;
    console.log(num);*/
    printMessage("안녕하세요");
}catch (e) {
    console.log(e);
}
console.log("프로그램 종료");

// 에러가 발생해도 끝까지 수행됨